---
Name: archipro-silverstripe-smart-enum
---
SilverStripe\Core\Injector\Injector:
  SmartEnum:
    class: ArchiPro\Silverstripe\SmartEnum\DBSmartEnum

SilverStripe\ORM\DataObject:
  extensions:
    - ArchiPro\Silverstripe\SmartEnum\SmartEnumDataExtension
